# Assignment 02

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:
a = np.array([[[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10,11,12,13,14]]])
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [7]:
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
a.reshape(1,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
a = np.random.rand((25)).reshape(5,5)
np.square(a)

array([[0.11181442, 0.09624732, 0.35703084, 0.50974304, 0.25067584],
       [0.1563451 , 0.10017873, 0.00271404, 0.32711522, 0.15983379],
       [0.938519  , 0.15472612, 0.00247891, 0.00109948, 0.39433022],
       [0.90959251, 0.34293219, 0.18383224, 0.66455561, 0.13407824],
       [0.34289773, 0.56126391, 0.81388651, 0.07867948, 0.71494347]])

## Question:8

### Create 5x6 an array and find the mean?

In [9]:
a = np.random.rand((30)).reshape(5,6)
np.mean(a)

0.4318819243805972

## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
np.std(a)

0.24905837701627906

## Question:10

### Find the median of the previous array in Q8?

In [11]:
np.median(a)

0.39014928675698196

## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
a.T

array([[0.62067245, 0.62238201, 0.85887096, 0.17352195, 0.10625451],
       [0.38897276, 0.1811746 , 0.38988812, 0.44506288, 0.1600652 ],
       [0.58104054, 0.38369678, 0.370973  , 0.34051545, 0.73262444],
       [0.391426  , 0.80663567, 0.14451092, 0.39041045, 0.12624816],
       [0.77259062, 0.78665742, 0.08594907, 0.05690698, 0.11770829],
       [0.76259092, 0.75549096, 0.48568095, 0.57538043, 0.34255525]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [13]:
a = np.random.rand((16)).reshape(4,4)
np.trace(a)

1.6563888427956213

## Question:13

### Find the determinant of the previous array in Q12?

In [14]:
np.linalg.det(a)

-0.11858738004504636

## Question:14

### Find the 5th and 95th percentile of an array?

In [15]:
print(a)
print("5th percentile : ",np.percentile(a,5))
print("95th percentile : ",np.percentile(a,95))

[[0.51449885 0.20040164 0.12868057 0.84989263]
 [0.13844733 0.13749648 0.15301858 0.98458191]
 [0.42736189 0.17633706 0.55796898 0.04414303]
 [0.86992577 0.81114549 0.27712114 0.44642453]]
5th percentile :  0.10754618546263006
95th percentile :  0.8985898047854874


## Question:15

### How to find if a given array has any null values?

In [16]:
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  np.nan,  8,  9, 10, 11, 12, 13, 14])
np.isnan(a).any()

True