# Assignment 01
Implentation of any 50 numpy methods or attribute codes in jupyter notebook

In [1]:
import numpy as np

## 1.

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
 %time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 29.9 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 1.33 s
Wall time: 1.42 s


## 2.

In [5]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

## 3.

In [6]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## 4.

In [7]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 5.

In [8]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 6.

In [9]:
arr = np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 7.

In [10]:
arr = np.empty([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 8.

In [11]:
arr = np.full([3,3],10)
arr

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## 9.

In [12]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 10.

In [13]:
arr = np.random.rand(36).reshape(4,3,3)
arr

array([[[0.14003072, 0.06918114, 0.40735889],
        [0.97175625, 0.08290781, 0.07331748],
        [0.47391931, 0.83375263, 0.3472523 ]],

       [[0.57748525, 0.21897897, 0.64097509],
        [0.73091355, 0.42072616, 0.15799219],
        [0.52346872, 0.60165482, 0.21222606]],

       [[0.08635283, 0.46328567, 0.74721001],
        [0.01322015, 0.75707039, 0.90053097],
        [0.66775735, 0.26510243, 0.22579437]],

       [[0.61709517, 0.69559642, 0.27118314],
        [0.83703927, 0.44246238, 0.87826395],
        [0.23507171, 0.27359111, 0.66668071]]])

## 11.

In [14]:
arr.shape

(4, 3, 3)

## 12.

In [15]:
arr.size

36

## 13.

In [16]:
arr.dtype

dtype('float64')

## 14.

In [17]:
arr.ndim

3

## 15.

In [18]:
arr1 = np.asarray(arr,dtype="int8")
arr1 

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int8)

## 16.

In [19]:
arr = arr1.astype("float64")
arr 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## 17.

In [20]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[7., 4., 7.], [1., 0., 4.]])

In [21]:
arr1 + 2

array([[3., 4., 5.],
       [6., 7., 8.]])

## 18.

In [22]:
arr1 + arr1

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

## 19.

In [23]:
arr1 * 8

array([[ 8., 16., 24.],
       [32., 40., 48.]])

## 20.

In [24]:
arr1 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

## 21.

In [25]:
arr1 > arr2

array([[False, False, False],
       [ True,  True,  True]])

## 22.

In [26]:
arr1[arr1>5]

array([6.])

## 23.

In [27]:
arr = (np.random.rand(25).reshape(5,5))*100
arr1 = arr.astype("int32")
arr1

array([[99, 47, 48, 21, 85],
       [63, 38, 86, 15, 96],
       [ 8, 99,  7, 35,  8],
       [47, 47, 94, 21, 14],
       [29, 66, 69, 50, 65]])

## 24.

In [28]:
arr1[0]

array([99, 47, 48, 21, 85])

## 25.

In [29]:
arr1[0][0]

99

## 26.

In [30]:
arr1[0:2]

array([[99, 47, 48, 21, 85],
       [63, 38, 86, 15, 96]])

## 27.

In [31]:
arr1[:,1:3]

array([[47, 48],
       [38, 86],
       [99,  7],
       [47, 94],
       [66, 69]])

## 28.

In [32]:
arr1[0:2,1:2]

array([[47],
       [38]])

## 29.

In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will'])
arr1[[ True, False, False,  True, False]]

array([[99, 47, 48, 21, 85],
       [47, 47, 94, 21, 14]])

## 30.

In [34]:
arr1[names == "Will"]

array([[ 8, 99,  7, 35,  8],
       [29, 66, 69, 50, 65]])

## 31.

In [35]:
arr1[names == "Will"] = 0
arr1

array([[99, 47, 48, 21, 85],
       [63, 38, 86, 15, 96],
       [ 0,  0,  0,  0,  0],
       [47, 47, 94, 21, 14],
       [ 0,  0,  0,  0,  0]])

## 32.

In [36]:
arr1

array([[99, 47, 48, 21, 85],
       [63, 38, 86, 15, 96],
       [ 0,  0,  0,  0,  0],
       [47, 47, 94, 21, 14],
       [ 0,  0,  0,  0,  0]])

In [37]:
arr1.T

array([[99, 63,  0, 47,  0],
       [47, 38,  0, 47,  0],
       [48, 86,  0, 94,  0],
       [21, 15,  0, 21,  0],
       [85, 96,  0, 14,  0]])

## 33.

In [38]:
np.sqrt(arr1)

array([[9.94987437, 6.8556546 , 6.92820323, 4.58257569, 9.21954446],
       [7.93725393, 6.164414  , 9.2736185 , 3.87298335, 9.79795897],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [6.8556546 , 6.8556546 , 9.69535971, 4.58257569, 3.74165739],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

## 34.

In [39]:
np.exp(arr1)

array([[9.88903032e+42, 2.58131289e+20, 7.01673591e+20, 1.31881573e+09,
        8.22301271e+36],
       [2.29378316e+27, 3.18559318e+16, 2.23524660e+37, 3.26901737e+06,
        4.92345829e+41],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00],
       [2.58131289e+20, 2.58131289e+20, 6.66317622e+40, 1.31881573e+09,
        1.20260428e+06],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00]])

## 35.

In [40]:
arr1

array([[99, 47, 48, 21, 85],
       [63, 38, 86, 15, 96],
       [ 0,  0,  0,  0,  0],
       [47, 47, 94, 21, 14],
       [ 0,  0,  0,  0,  0]])

In [41]:
np.log(arr1)

C:\Users\Hassan\AppData\Local\Temp\ipykernel_3748\2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([[4.59511985, 3.8501476 , 3.87120101, 3.04452244, 4.44265126],
       [4.14313473, 3.63758616, 4.4543473 , 2.7080502 , 4.56434819],
       [      -inf,       -inf,       -inf,       -inf,       -inf],
       [3.8501476 , 3.8501476 , 4.54329478, 3.04452244, 2.63905733],
       [      -inf,       -inf,       -inf,       -inf,       -inf]])

## 36.

In [42]:
arr = (np.random.rand(25).reshape(5,5))*100
arr1 = arr.astype("int32")
arr1

array([[13, 22, 69, 25, 10],
       [89, 28, 93, 20, 25],
       [16, 34, 47,  9, 79],
       [64, 22, 98, 61, 63],
       [ 1, 53, 98, 56, 87]])

In [43]:
arr = (np.random.rand(25).reshape(5,5))*100
arr2 = arr.astype("int32")
arr2

array([[70, 89, 31, 78, 37],
       [64,  2, 56, 39, 88],
       [61, 49, 49,  0,  4],
       [67, 42,  4, 70, 18],
       [59, 61, 82, 51,  1]])

In [44]:
np.add(arr1,arr2)

array([[ 83, 111, 100, 103,  47],
       [153,  30, 149,  59, 113],
       [ 77,  83,  96,   9,  83],
       [131,  64, 102, 131,  81],
       [ 60, 114, 180, 107,  88]])

## 37.

In [45]:
np.subtract(arr1,arr2)

array([[-57, -67,  38, -53, -27],
       [ 25,  26,  37, -19, -63],
       [-45, -15,  -2,   9,  75],
       [ -3, -20,  94,  -9,  45],
       [-58,  -8,  16,   5,  86]])

## 38.

In [46]:
np.less(arr1,arr2)

array([[ True,  True, False,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True, False, False],
       [ True,  True, False,  True, False],
       [ True,  True, False, False, False]])

## 39.

In [47]:
np.maximum(arr1,arr2)

array([[70, 89, 69, 78, 37],
       [89, 28, 93, 39, 88],
       [61, 49, 49,  9, 79],
       [67, 42, 98, 70, 63],
       [59, 61, 98, 56, 87]])

## 40.

In [48]:
np.sum(arr2)

1172

## 41.

In [49]:
np.mean(arr2)

46.88

## 42.

In [50]:
np.cumsum(arr2)

array([  70,  159,  190,  268,  305,  369,  371,  427,  466,  554,  615,
        664,  713,  713,  717,  784,  826,  830,  900,  918,  977, 1038,
       1120, 1171, 1172])

## 43.

In [51]:
np.cumprod(arr2)

array([         70,        6230,      193130,    15064140,   557373180,
        1312145152, -1670676992,   931368960,  1963651072,  1002602496,
        1029210112, -1108312064,  1527283712,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0])

## 44.

In [52]:
arr1

array([[13, 22, 69, 25, 10],
       [89, 28, 93, 20, 25],
       [16, 34, 47,  9, 79],
       [64, 22, 98, 61, 63],
       [ 1, 53, 98, 56, 87]])

In [53]:
np.diag(arr1)

array([13, 28, 47, 61, 87])

## 45.

In [54]:
np.dot(arr1,arr2)

array([[ 8792,  6242,  5936,  4132,  3153],
       [16510, 14899, 11014, 10709,  6514],
       [11427,  8992, 11217,  7233,  4013],
       [19670, 16947, 13428, 13333,  5857],
       [18325, 12656, 15159, 10502,  6188]])

## 46.

In [55]:
np.trace(arr1)

236

## 47.

In [56]:
np.min(arr1)

1

## 48.

In [57]:
np.vstack((arr1,arr2))

array([[13, 22, 69, 25, 10],
       [89, 28, 93, 20, 25],
       [16, 34, 47,  9, 79],
       [64, 22, 98, 61, 63],
       [ 1, 53, 98, 56, 87],
       [70, 89, 31, 78, 37],
       [64,  2, 56, 39, 88],
       [61, 49, 49,  0,  4],
       [67, 42,  4, 70, 18],
       [59, 61, 82, 51,  1]])

## 49.

In [58]:
np.hstack((arr1,arr2))

array([[13, 22, 69, 25, 10, 70, 89, 31, 78, 37],
       [89, 28, 93, 20, 25, 64,  2, 56, 39, 88],
       [16, 34, 47,  9, 79, 61, 49, 49,  0,  4],
       [64, 22, 98, 61, 63, 67, 42,  4, 70, 18],
       [ 1, 53, 98, 56, 87, 59, 61, 82, 51,  1]])

## 50.

In [59]:
np.stack((arr1,arr2))

array([[[13, 22, 69, 25, 10],
        [89, 28, 93, 20, 25],
        [16, 34, 47,  9, 79],
        [64, 22, 98, 61, 63],
        [ 1, 53, 98, 56, 87]],

       [[70, 89, 31, 78, 37],
        [64,  2, 56, 39, 88],
        [61, 49, 49,  0,  4],
        [67, 42,  4, 70, 18],
        [59, 61, 82, 51,  1]]])